-- Runs in schema "bioskop" (spring.flyway.schemas), not exposed by the Supabase Data API

create table users (
    user_id  integer generated by default as identity primary key,
    username varchar(50)  not null unique,
    email    varchar(255) not null unique,
    password varchar(100) not null,
    role     varchar(10)  not null default 'USER'
);

create table films (
    film_id    integer generated by default as identity primary key,
    film_code  varchar(20)  not null unique,
    film_name  varchar(255) not null,
    is_showing boolean      not null
);

create table seats (
    studio_name char(1)    not null,
    seats_code  varchar(5) not null,
    primary key (studio_name, seats_code)
);

create table schedules (
    schedule_id     integer generated by default as identity primary key,
    film_id         integer not null references films (film_id),
    studio_name     char(1) not null,
    film_date       date    not null,
    film_start_time time    not null,
    film_end_time   time    not null,
    ticket_price    integer not null check (ticket_price >= 0),
    unique (schedule_id, studio_name)
);

create table tickets (
    ticket_id   integer generated by default as identity primary key,
    user_id     integer    not null references users (user_id),
    schedule_id integer    not null,
    studio_name char(1)    not null,
    seats_code  varchar(5) not null,
    -- the seat must exist in the schedule's studio
    foreign key (schedule_id, studio_name) references schedules (schedule_id, studio_name),
    foreign key (studio_name, seats_code) references seats (studio_name, seats_code),
    -- one ticket per seat per schedule
    unique (schedule_id, seats_code)
);

-- Studios A-C, rows A-E, seats 1-10
insert into seats (studio_name, seats_code)
select s.studio, r.seat_row || n.num
from (values ('A'), ('B'), ('C')) as s (studio)
cross join (values ('A'), ('B'), ('C'), ('D'), ('E')) as r (seat_row)
cross join (values ('1'), ('2'), ('3'), ('4'), ('5'), ('6'), ('7'), ('8'), ('9'), ('10')) as n (num);
